services:
  postgres:
    image: postgres
    container_name: postgres2-card-holder
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9002:8080